// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: server.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UpdatersClient is the client API for Updaters service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UpdatersClient interface {
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateRespons, error)
}

type updatersClient struct {
	cc grpc.ClientConnInterface
}

func NewUpdatersClient(cc grpc.ClientConnInterface) UpdatersClient {
	return &updatersClient{cc}
}

func (c *updatersClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateRespons, error) {
	out := new(UpdateRespons)
	err := c.cc.Invoke(ctx, "/api.Updaters/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdatersServer is the server API for Updaters service.
// All implementations must embed UnimplementedUpdatersServer
// for forward compatibility
type UpdatersServer interface {
	Update(context.Context, *UpdateRequest) (*UpdateRespons, error)
	mustEmbedUnimplementedUpdatersServer()
}

// UnimplementedUpdatersServer must be embedded to have forward compatible implementations.
type UnimplementedUpdatersServer struct {
}

func (UnimplementedUpdatersServer) Update(context.Context, *UpdateRequest) (*UpdateRespons, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedUpdatersServer) mustEmbedUnimplementedUpdatersServer() {}

// UnsafeUpdatersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpdatersServer will
// result in compilation errors.
type UnsafeUpdatersServer interface {
	mustEmbedUnimplementedUpdatersServer()
}

func RegisterUpdatersServer(s grpc.ServiceRegistrar, srv UpdatersServer) {
	s.RegisterService(&Updaters_ServiceDesc, srv)
}

func _Updaters_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdatersServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Updaters/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdatersServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Updaters_ServiceDesc is the grpc.ServiceDesc for Updaters service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Updaters_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Updaters",
	HandlerType: (*UpdatersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Update",
			Handler:    _Updaters_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}
